<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.tibco.com/schemas/soap_jms/Schemas/Schema.xsd3" xmlns:tns="http://xmlns.example.com/1578470743754" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns2="http://www.tibco.com/schemas/soap_jms/Schemas/Schema.xsd4" targetNamespace="http://xmlns.example.com/1578470743754">
    <import namespace="http://www.tibco.com/schemas/soap_jms/Schemas/Schema.xsd3" location="../Schemas/CalculatorInputs.xsd"/>
    <import namespace="http://www.tibco.com/schemas/soap_jms/Schemas/Schema.xsd4" location="../Schemas/CalculatorOuputs.xsd"/>
    <message name="CalculatorInputRequest">
        <part name="Request" element="ns:CalculatorRequestInputs"/>
    </message>
    <message name="CalculatorOutputResponse">
        <part name="Response" element="ns2:CalculatorOutputResponse"/>
    </message>
    <portType name="CalculatorPortType">
        <operation name="GetCalculations">
            <input message="tns:CalculatorInputRequest"/>
            <output message="tns:CalculatorOutputResponse"/>
        </operation>
    </portType>
</definitions>